import json, zipfile, sys, collections, re
sys.stdout.reconfigure(encoding="utf-8")
z = zipfile.ZipFile("阅读APP-内置主流书源.apk")
data = json.loads(z.read("assets/defaultData/bookSources.json").decode("utf-8"))
# 结构统计
fields = collections.Counter()
for it in data: fields.update(it.keys())
print("字段覆盖 Top:", fields.most_common(12))
types = collections.Counter(it.get("bookSourceType") for it in data)
print("bookSourceType 分布 (0=文本,1=音频,2=图片,3=文件):", dict(types))
groups = collections.Counter(it.get("bookSourceGroup","") for it in data)
print("分组 Top12:", groups.most_common(12))
empty_search = sum(1 for it in data if not it.get("searchUrl") and not it.get("ruleSearch"))
print("无搜索规则的书源:", empty_search)
enabled = sum(1 for it in data if it.get("enabled", True) is not False)
print("enabled!=False:", enabled, "/", len(data))
names = collections.Counter(it.get("bookSourceName") for it in data)
print("重名 Top8:", names.most_common(8))
